- action:
  - alias: Alert for Door
    data:
      message: Door 1 Open
    service: persistent_notification.create
  - alias: Alert for Door to Tods iPhone
    data:
      message: Door 1 Open
    service: notify.ios_tods_iphone
  alias: Door Sensor 1 Open
  condition: []
  id: '1510275018495'
  trigger:
  - entity_id: binary_sensor.door_sensor_1_sensor
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: Door 1 Closed to Tods iPhone
    data:
      message: Door 1 Closed
    service: notify.ios_tods_iphone
  - alias: Door 1 Closed
    data:
      message: Door 1 Closed
    service: persistent_notification.create
  alias: Door Sensor 1 Closed
  condition: []
  id: '1510277070537'
  trigger:
  - entity_id: binary_sensor.door_sensor_1_sensor
    from: 'on'
    platform: state
    to: 'off'
