homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 241
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
#frontend:
#  extra_html_url:
#   - custom_ui/state-card-floorplan.html
#
## Floorplan
#mqtt:
#binary_sensor:
#  - platform: mqtt
#    state_topic: dummy/floorplan/sensor
#    name: Floorplan
#
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml   
#/Floorplan

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret http_base_url
  ssl_certificate: /etc/letsencrypt/live/home.todschmidt.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/home.todschmidt.com/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

mqtt:

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

ios: !include ios.yaml

climate: !include climate.yaml
automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_list sensors/
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups/
scene: !include_dir_merge_list scenes/
camera: !include camera.yaml
light: !include light.yaml
input_boolean: !include input_boolean.yaml
input_number: !include_dir_merge_named input_number/
binary_sensor: !include binary_sensor.yaml
shell_command: !include_dir_merge_named shell_command/
media_player: !include media_player.yaml
switch: !include_dir_merge_list switch/
notify: !include notify.yaml
script: !include scripts.yaml

# Custom
variable: !include variables.yaml

