- platform: roku
- platform: plex
- platform: mpd
  host: 192.168.1.19
  name: mopidy
#- platform: snapcast
#  host: 192.168.1.201
- platform: gstreamer
  name: Downstairs
  pipeline: "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo"
#- platform: spotify
#  client_id: !secret spotify_client_id
#  client_secret: !secret spotify_client_secret
#  aliases:
#    abc123def456: 'Living Room'
#    9183abas000: 'Bed Room'

