- alias: Turn off Downstairs Thermostat at 10:45
  trigger:
    - platform: time
      at: '22:45:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '68'
        cooling_temp: '90'

- alias: Turn Downstairs Thermostat on at 06:00
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '72'
        cooling_temp: '90'

- alias: Turn Downstairs Heat Down when not home
  trigger:
    - platform: state 
      entity_id: group.household
      from: 'home'
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '65'
        cooling_temp: '90'

- alias: Reset Downstairs Heat
  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '72'
        cooling_temp: '90'


