#################################################################
## Vacation Mode Automations
#################################################################

        ##########################################################
        ## Turn on Vacation Mode when Gone 24 Hours
        ##########################################################

- alias: Vacation - Turn on when Gone 24 Hours
  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode
      
        ##########################################################
        ## Turn off Vacation Mode when Home
        ##########################################################

- alias: Vacation - Turn off when Home
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode
      
